#!/bin/sh
# See https://www.xymon.com/help/xymon-alerts.html#scripts

if [ "$RECOVERED" = 1 ]; then
    echo "RECOVERED: $BBHOSTSVC is $BBCOLORLEVEL:\n\n$BBALPHAMSG";
else
    echo "$BBHOSTSVC is $BBCOLORLEVEL:\n\n$BBALPHAMSG";
fi | cut -c1-4095 -z | /usr/local/bin/telegram-bot-send-to $RCPT
